print("----WELCOME TO MY TO-DO LIST----")
list=[]
task1=input("Enter task:")
list.append(task1)
task2=input("Enter task:")
list.append(task2)
task3=input("Enter task:")
list.append(task3)
task4=input("Enter task:")
list.append(task4)
task5=input("Enter task:")
list.append(task5)
print("view list:")
print(list)
print("removed task:")
print(list.pop(2))